window.NCC_CHAPTERS = [{
  id: "h1",
  section: "H",
  title: "H1 Structure",
  titleZh: "H1 结构",
  source: "NCC 2025 Volume Two",
  summaryEn: "Part H1 explains how Class 1 and 10 buildings must remain structurally reliable under the actions they can reasonably experience during construction and use. It covers site preparation, footings and slabs, masonry, framing, cladding, glazing, earthquake and flood conditions, deck and balcony attachments, and piled footings. The correct pathway depends on the site, loads, materials and construction system.",
  summaryZh: "H1 部分说明 1 类和 10 类建筑在施工和使用期间面对可合理预见的作用时，如何保持结构可靠。内容包括场地准备、基础和楼板、砌体、框架、覆层、玻璃、地震和洪水条件、露台与阳台连接，以及桩基础。正确的合规路径取决于场地、荷载、材料和施工系统。",
  summaryCitation: "H1O1–H1D12, pp. 89–110",
  questions: [
    ["What is the purpose of Part H1?", "H1 部分的目的是什么？", "It makes sure a Class 1 or 10 building has a structure that is safe and reliable for its expected conditions.", "它确保 1 类或 10 类建筑在预期条件下具有安全、可靠的结构。", "H1O1, p. 89"],
    ["What does structural reliability mean in plain English?", "用简单英语说，结构可靠性是什么意思？", "The building must safely resist the loads and actions it is expected to face during its life, rather than failing or becoming unsafe.", "建筑必须在使用寿命内安全抵抗预期荷载和作用，而不会失效或变得不安全。", "H1P1, p. 89"],
    ["Why do flood areas need separate consideration?", "为什么洪水区域需要单独考虑？", "Floodwater can place unusual loads on a building. The NCC therefore has a separate performance requirement for buildings in flood areas.", "洪水会对建筑施加异常荷载，因此 NCC 对洪水区域内的建筑设有单独的性能要求。", "H1P2, p. 92"],
    ["What is a Deemed-to-Satisfy solution for structure?", "结构方面的视为满足方案是什么？", "It is the standard NCC pathway: follow the listed structural provisions and the related Housing Provisions instead of proving a custom solution another way.", "这是 NCC 的标准路径：遵循列出的结构规定和相关住房条文，而不是用其他方式证明定制方案。", "H1D1–H1D2, pp. 94–95"],
    ["Why is site preparation important before construction starts?", "为什么施工前的场地准备很重要？", "The ground and site conditions affect how the building is supported. Good preparation helps ensure the structure is built on suitable conditions.", "地面和场地条件会影响建筑如何获得支撑。良好的场地准备有助于确保结构建在合适的条件上。", "H1D3, p. 95"],
    ["What must you understand about footings and slabs?", "关于基础和楼板，您必须了解什么？", "Footings and slabs transfer building loads into the ground. Their design must suit the site and the building so movement or failure is controlled.", "基础和楼板将建筑荷载传递到地面。其设计必须适合场地和建筑，以控制移动或失效。", "H1D4, p. 96"],
    ["Why does masonry need its own structural rules?", "为什么砌体需要自己的结构规则？", "Masonry walls have particular strength, support and construction requirements. The NCC points to the relevant provisions rather than treating every wall the same.", "砌体墙有特定的强度、支撑和施工要求。NCC 指向相关规定，而不是把所有墙都同样处理。", "H1D5, p. 98"],
    ["What is the key question for framing?", "框架结构最关键的问题是什么？", "Ask whether the wall, floor and roof framing system is suitable for the loads, span, connections and conditions of this particular building.", "应问：墙体、楼板和屋顶框架系统是否适合该建筑的荷载、跨度、连接和条件。", "H1D6, p. 100"],
    ["Why are roof and wall cladding structural issues?", "为什么屋顶和墙面覆层是结构问题？", "Cladding must remain attached and perform under expected wind and weather actions. It is not only a visual finish.", "覆层必须在预期风力和天气作用下保持牢固并发挥性能；它不仅仅是外观饰面。", "H1D7, p. 105"],
    ["When do glazing, earthquake and flood provisions matter?", "玻璃、地震和洪水条文何时适用？", "They matter when the site or building triggers those risks. Check glazing requirements, the relevant earthquake area, and whether the site is a flood hazard area.", "当场地或建筑涉及这些风险时，它们就适用。应检查玻璃要求、相关地震区域，以及场地是否属于洪水危险区域。", "H1D8–H1D10, pp. 107–109"]
  ]
}, {
  id: "a1",
  section: "A",
  title: "A1 Interpreting the NCC",
  titleZh: "A1 解读 NCC",
  source: "NCC 2025 Volume Two",
  summaryEn: "Part A1 is the instruction manual for reading the NCC. It tells you which Volume applies, which text is mandatory, how defined words must be read, and how to use Application, Limitation, Exemption, Notes and Figures. Read A1 before applying a technical clause so you know whether it applies, what it means and whether a State or Territory variation matters.",
  summaryZh: "A1 部分是阅读 NCC 的说明书。它说明哪一卷适用、哪些文字是强制性的、如何理解定义词，以及如何使用适用条款、限制条款、豁免条款、注释和图示。在应用任何技术条款之前，应先阅读 A1，以了解该条款是否适用、含义是什么，以及是否存在州或领地的变更。",
  summaryCitation: "A1G1–A1G4, pp. 38–40",
  questions: [
    ["What is Part A1 for?", "A1 部分有什么作用？", "It explains how to read and apply the NCC. Learn these interpretation rules before using technical requirements in later sections.", "它说明如何阅读和应用 NCC。在使用后续章节的技术要求之前，先学习这些解释规则。", "A1G4, pp. 38–39"],
    ["Which building work belongs in NCC Volume Two?", "哪些建筑工作属于 NCC 第二卷？", "Volume Two covers Class 1 and 10a buildings, certain Class 10b structures, and Class 10c private bushfire shelters, subject to the stated access exceptions.", "第二卷涵盖 1 类和 10a 类建筑、某些 10b 类构筑物，以及 10c 类私人丛林火灾避难所，但受列明的无障碍例外限制。", "A1G2, p. 38"],
    ["Why must you know the difference between the three NCC volumes?", "为什么必须了解 NCC 三卷之间的区别？", "Each volume has a different scope. Using the wrong volume can mean you miss the rules that apply to the building or its plumbing work.", "每一卷都有不同的适用范围。使用错误的卷册可能会遗漏适用于建筑或管道工作的规则。", "A1G1–A1G3, p. 38"],
    ["Which NCC content is informative rather than mandatory?", "哪些 NCC 内容是说明性的而不是强制性的？", "Explanatory information and introduction material are non-mandatory. They help you understand the Code but do not replace the enforceable requirements.", "解释性信息和导言材料不是强制性的。它们帮助您理解规范，但不能取代可执行的要求。", "A1G4(1), pp. 38–39"],
    ["How should italic words be read?", "斜体词应如何理解？", "Use the definition in Schedule 1 unless the context clearly means something different. Also check the relevant State or Territory appendix.", "除非上下文显然另有含义，否则使用附表 1 中的定义。还应检查相关州或领地附录。", "A1G4(2), p. 39"],
    ["What does ‘to the degree necessary’ mean?", "“在必要的程度上”是什么意思？", "It requires you to consider all stated criteria for the actual situation. In some cases, no specific measure may be needed after that assessment.", "它要求您根据实际情况考虑所有列出的标准。在某些情况下，评估后可能不需要具体措施。", "A1G4(3)(c), p. 39"],
    ["What is the difference between an Application, Limitation and Exemption?", "适用条款、限制条款和豁免条款有什么区别？", "All three are mandatory: Application tells you where a rule applies; Limitation narrows when it applies; Exemption tells you when compliance is not required.", "三者都是强制性的：适用条款说明规则在哪里适用；限制条款缩小适用条件；豁免条款说明何时不需要遵守。", "A1G4(3)(d)–(f), p. 39"],
    ["Are Notes and Figures optional?", "注释和图示是可选的吗？", "A Note forms part of the provision and gives additional mandatory instructions. A Figure illustrates the text but is not the complete design information by itself.", "注释构成条文的一部分，并提供额外的强制指示。图示用于说明文字，但本身并不构成完整的设计信息。", "A1G4(3)(g)–(h), p. 39"],
    ["When the NCC says ‘Class 10’, does it mean every Class 10 type?", "当 NCC 写“10 类”时，是否指所有 10 类类型？", "Yes. A reference to a building class includes all its sub-classifications unless the Code names a specific sub-classification.", "是的。对建筑类别的引用包括其所有子类别，除非规范明确点名某一子类别。", "A1G4(4)–(6), p. 39"],
    ["Why do building parts matter when interpreting a requirement?", "解释一项要求时，为什么建筑的不同部分很重要？", "In a mixed-classification building, a reference to a building can mean the relevant part. Each part must meet the provisions that apply to its classification.", "在混合分类建筑中，对建筑的引用可能指相关部分。每个部分必须满足适用于其分类的条文。", "A1G4 and Explanatory Information, p. 40"]
  ]
}, {
  id: "a2",
  section: "A",
  title: "A2 Compliance with the NCC",
  titleZh: "A2 遵守 NCC",
  source: "NCC 2025 Volume Two",
  summaryEn: "Part A2 explains how a building solution demonstrates NCC compliance. Every solution must meet the Governing Requirements and relevant Performance Requirements. You may follow the prescriptive Deemed-to-Satisfy pathway, develop a Performance Solution, or combine both. A Performance Solution needs the right assessment method, a documented design process and a final report that proves the required outcome.",
  summaryZh: "A2 部分说明建筑方案如何证明符合 NCC。每个方案必须满足管理要求和相关性能要求。您可以遵循规定性的视为满足路径、制定性能解决方案，或将两者结合。性能解决方案需要合适的评估方法、记录在案的设计过程，以及证明达到所需结果的最终报告。",
  summaryCitation: "A2G1–A2G4, pp. 41–44",
  questions: [
    ["What must a solution comply with to meet the NCC?", "一个方案必须遵守什么才能符合 NCC？", "It must comply with the Governing Requirements and satisfy the relevant Performance Requirements.", "它必须遵守管理要求并满足相关性能要求。", "A2G1, p. 41"],
    ["What are the three compliance pathways?", "三种合规路径是什么？", "You may use a Performance Solution, a Deemed-to-Satisfy Solution, or a combination of both.", "您可以使用性能解决方案、视为满足方案，或两者的组合。", "A2G1(2), p. 41"],
    ["What is a Performance Solution?", "什么是性能解决方案？", "It is a tailored way to show the relevant Performance Requirements are met, or that the result is at least equivalent to the DTS provisions.", "它是一种定制方法，用于证明满足相关性能要求，或结果至少等同于 DTS 条文。", "A2G2(1), p. 41"],
    ["How can a Performance Solution be assessed?", "如何评估性能解决方案？", "The NCC allows evidence of suitability, verification methods, expert judgement, or comparison with DTS provisions, alone or combined where allowed.", "NCC 允许使用适用性证据、验证方法、专家判断或与 DTS 条文比较，可在允许时单独或组合使用。", "A2G2(2), pp. 41–42"],
    ["What must happen before analysing a Performance Solution?", "分析性能解决方案之前必须做什么？", "Prepare a performance-based design brief with relevant stakeholders. It sets the analysis and acceptance criteria.", "必须与相关利益方编制基于性能的设计简报。它确定分析和验收标准。", "A2G2(4)(a), p. 42"],
    ["What report is required after a Performance Solution is assessed?", "评估性能解决方案后需要什么报告？", "The final report records applicable requirements, assessment methods, analysis, confirmation of compliance, and any conditions or limits.", "最终报告记录适用要求、评估方法、分析、合规确认以及任何条件或限制。", "A2G2(4)(d), p. 42"],
    ["What is a Deemed-to-Satisfy Solution?", "什么是视为满足方案？", "If it complies with the stated DTS provisions, it is deemed to have met the Performance Requirements.", "如果它符合规定的 DTS 条文，则视为已满足性能要求。", "A2G3(1), p. 42"],
    ["Can a DTS solution still need evidence or expert judgement?", "DTS 方案仍然需要证据或专家判断吗？", "Yes. The NCC lists evidence of suitability and expert judgement as assessment methods for demonstrating DTS compliance.", "是的。NCC 将适用性证据和专家判断列为证明 DTS 合规的评估方法。", "A2G3(2), p. 42"],
    ["Can Performance and DTS solutions be combined?", "性能方案和 DTS 方案可以组合吗？", "Yes. Use the relevant A2G2 process for the Performance part and A2G3 for the DTS part, while identifying all affected requirements.", "可以。性能部分使用相关 A2G2 流程，DTS 部分使用 A2G3，同时识别所有受影响的要求。", "A2G4, p. 43"],
    ["Why must you identify requirements in other Parts?", "为什么必须识别其他部分的要求？", "A design choice can affect more than one part of the NCC. You must identify the related Performance Requirements, not assess one clause in isolation.", "一个设计选择可能影响 NCC 的多个部分。您必须识别相关性能要求，而不能孤立地评估一个条款。", "A2G2(3), A2G4(3), pp. 42–43"]
  ]
}, {
  id: "a3",
  section: "A",
  title: "A3 Application of the NCC in States and Territories",
  titleZh: "A3 NCC 在各州和领地的适用",
  source: "NCC 2025 Volume Two",
  summaryEn: "Part A3 explains that the NCC is applied through each State or Territory's legislation. Volume Two contains the national requirements in Sections A and H, but you must also check the applicable jurisdictional schedule for variations, additions and deletions. Local legislation can give the NCC legal effect and can override an NCC provision, so identifying the project location is an essential first step.",
  summaryZh: "A3 部分说明 NCC 通过各州或领地的法律实施。第二卷包含 A 节和 H 节的全国性要求，但还必须检查适用司法辖区附表中的变更、增加和删除内容。当地法律赋予 NCC 法律效力，并可能优先于 NCC 条文，因此确认项目所在地是首要步骤。",
  summaryCitation: "A3G1, p. 45",
  questions: [
    ["What is included in NCC Volume Two?", "NCC 第二卷包括什么？", "It contains Sections A and H together with the schedules associated with this Volume.", "它包括 A 节、H 节以及与本卷相关的附表。", "A3G1(1), p. 45"],
    ["Why is the project location important when using the NCC?", "使用 NCC 时，为什么项目所在地很重要？", "The State or Territory determines which local variations, additions, deletions and legislation apply to the work.", "项目所在州或领地决定适用哪些当地变更、增加、删除内容和法律。", "A3G1(2)–(3), p. 45"],
    ["Must State and Territory variations be followed?", "是否必须遵守州和领地的变更？", "Yes. Applicable variations, additions and deletions must be complied with together with the national NCC provisions.", "是的。适用的变更、增加和删除内容必须与 NCC 全国性条文一起遵守。", "A3G1(2), p. 45"],
    ["Can State or Territory legislation override the NCC?", "州或领地法律可以优先于 NCC 吗？", "Yes. If the jurisdiction's legislation overrides an NCC provision, the legislation takes priority.", "可以。如果该司法辖区的法律凌驾于 NCC 条文之上，则以该法律为准。", "A3G1(3), p. 45"],
    ["Where do you find South Australian NCC variations?", "在哪里查找南澳大利亚州的 NCC 变更？", "For South Australia, check Schedule 8 and also confirm the current South Australian legislation that adopts or modifies the NCC.", "对于南澳大利亚州，应检查附表 8，并确认采用或修改 NCC 的现行南澳法律。", "A3G1(4)(f), p. 45"],
    ["Which schedule applies to the Commonwealth?", "哪个附表适用于澳大利亚联邦？", "Schedule 3 contains the Commonwealth provisions identified by Part A3.", "A3 部分指出，附表 3 包含澳大利亚联邦的相关规定。", "A3G1(4)(a), p. 45"],
    ["How are the jurisdictional schedules organised?", "各司法辖区附表如何编排？", "Schedules 4 to 11 cover the ACT, NSW, NT, Queensland, South Australia, Tasmania, Victoria and Western Australia respectively.", "附表 4 至 11 依次涵盖首都领地、新南威尔士、北领地、昆士兰、南澳、塔斯马尼亚、维多利亚和西澳。", "A3G1(4), p. 45"],
    ["Are jurisdictional changes shown only in the schedules?", "司法辖区的变更是否只显示在附表中？", "No. Variations and deletions are also identified throughout the NCC, so read both the main provision and the relevant schedule.", "不是。变更和删除内容也会在 NCC 全文中标明，因此应同时阅读主要条文和相关附表。", "A3G1 explanatory information, p. 45"],
    ["What gives the NCC legal effect?", "什么赋予 NCC 法律效力？", "The NCC gains legal effect when it is adopted through State or Territory building and plumbing legislation.", "NCC 通过州或领地的建筑和管道法律被采用后获得法律效力。", "A3G1 explanatory information, p. 45"],
    ["What practical check should you make before applying a technical rule?", "应用技术规则之前应进行什么实际检查？", "Confirm the building location, open the relevant jurisdictional schedule, and check whether local legislation changes the national rule.", "确认建筑所在地，打开相关司法辖区附表，并检查当地法律是否改变了全国性规则。", "A3G1, p. 45"]
  ]
}, {
  id: "a4",
  section: "A",
  title: "A4 Referenced Documents",
  titleZh: "A4 引用文件",
  source: "NCC 2025 Volume Two",
  summaryEn: "Part A4 controls how standards and other documents referenced by the NCC are used. Use only the edition listed in Schedule 2 or the permitted alternative register, and only for the context in which the NCC calls it up. The NCC takes priority if there is a conflict. Contractual clauses and provisions that depend on another person's approval are not automatically adopted. Keep a record of the exact document editions used for the design and approval.",
  summaryZh: "A4 部分规定如何使用 NCC 引用的标准和其他文件。只能使用附表 2 所列版本或获准的替代文件登记册版本，并且只能用于 NCC 引用它的具体情境。如有冲突，以 NCC 为准。合同条款以及依赖他人批准的规定不会自动被 NCC 采用。设计和审批时应记录所使用文件的准确版本。",
  summaryCitation: "A4G1–A4G3, pp. 46–48",
  questions: [
    ["Which edition of a referenced document should you use?", "应使用引用文件的哪个版本？", "Use the edition, issue or amendment listed in Schedule 2, unless an applicable alternative referenced document is permitted.", "应使用附表 2 所列的版本、期号或修订版，除非允许使用适用的替代引用文件。", "A4G1(1), p. 46"],
    ["Does a newly published standard automatically replace the listed edition?", "新发布的标准会自动取代所列版本吗？", "No. A newer edition is not an NCC referenced document until the NCC or the permitted alternative register identifies it.", "不会。除非 NCC 或获准的替代登记册明确列出，新版本不会自动成为 NCC 引用文件。", "A4G1(1), p. 46"],
    ["Does the whole referenced document always apply?", "引用文件的全部内容总是适用吗？", "No. It applies only in the context and to the extent that the NCC provision calls it up.", "不是。它只在 NCC 条文引用它的具体情境和范围内适用。", "A4G1(2), p. 46"],
    ["What is a primary referenced document?", "什么是主要引用文件？", "It is a document directly referenced by the NCC, such as a standard named in a Deemed-to-Satisfy provision.", "它是 NCC 直接引用的文件，例如视为满足条文中点名的标准。", "A4G1 explanatory information, p. 46"],
    ["What is a secondary referenced document?", "什么是次级引用文件？", "It is a document called up by a primary referenced document rather than directly by the NCC.", "它是由主要引用文件进一步引用、而不是由 NCC 直接引用的文件。", "A4G1 explanatory information, p. 46"],
    ["Which edition of a secondary document normally applies?", "次级文件通常适用哪个版本？", "Normally use the edition that existed when the primary referenced document was published, subject to any stated exception.", "通常使用主要引用文件发布时已存在的次级文件版本，但须遵守任何明确例外。", "A4G1(3), p. 46"],
    ["Can you mix listed and alternative editions in one DTS provision?", "可以在同一 DTS 条文中混用所列版本和替代版本吗？", "No. Do not mix the Schedule 2 edition with an alternative-register edition for the same DTS provision or Verification Method.", "不可以。在同一 DTS 条文或验证方法中，不得混用附表 2 版本和替代登记册版本。", "A4G1(4), p. 46"],
    ["Do State and Territory variations affect referenced documents?", "州和领地的变更会影响引用文件吗？", "They can. Check the applicable jurisdictional provisions before selecting the document and edition.", "会有可能。选择文件和版本之前，应检查适用的司法辖区规定。", "A4G1(5), p. 46"],
    ["Does Part A4 also apply to the Housing Provisions?", "A4 部分也适用于住房条文吗？", "Yes. The referenced-document rules apply when the Housing Provisions call up documents.", "是的。当住房条文引用文件时，这些引用文件规则同样适用。", "A4G1(6), p. 46"],
    ["What happens if the NCC conflicts with a referenced document?", "如果 NCC 与引用文件冲突怎么办？", "The NCC provision overrides the conflicting requirement in the primary or secondary referenced document.", "NCC 条文优先于主要或次级引用文件中与其冲突的要求。", "A4G2, p. 47"],
    ["Are contractual clauses in a referenced standard adopted by the NCC?", "引用标准中的合同条款会被 NCC 采用吗？", "No. Provisions dealing with contracts, rights, responsibilities, approvals, opinions or departures by agreement are not adopted merely because the document is referenced.", "不会。涉及合同、权利、责任、批准、意见或经协议偏离的规定，不会仅因文件被引用而被 NCC 采用。", "A4G3(1), p. 47"],
    ["Can a Performance Solution use a different document or edition?", "性能解决方案可以使用不同文件或版本吗？", "Potentially yes. Other documents or editions may support a Performance Solution if the assessment demonstrates that the relevant Performance Requirements are satisfied.", "有可能。若评估能证明满足相关性能要求，其他文件或版本可用于支持性能解决方案。", "A4G3 explanatory information, pp. 47–48"],
    ["Why should document editions be recorded?", "为什么应记录文件版本？", "Recording the exact editions in permits, certificates and design records makes the compliance basis clear and prevents later confusion.", "在许可证、证书和设计记录中记下准确版本，可明确合规依据并避免日后混淆。", "A4G1 explanatory information, p. 47"]
  ]
}, {
  id: "a5",
  section: "A",
  title: "A5 Documentation of Design and Construction",
  titleZh: "A5 设计与施工文件",
  source: "NCC 2025 Volume Two",
  summaryEn: "Part A5 is about proving that materials, products, construction systems and designs are suitable for their intended use. Evidence must be appropriate, current where required, complete and connected to the exact NCC requirement being demonstrated. The Part recognises certificates, accredited test reports, qualified professional reports and other properly supported documents, and adds specific evidence rules for fire performance, aluminium composite panels and NatHERS.",
  summaryZh: "A5 部分说明如何证明材料、产品、施工系统和设计适合其预定用途。证据必须适当、在需要时保持有效、内容完整，并对应所要证明的具体 NCC 要求。本部分认可证书、认可实验室测试报告、合资格专业人员报告及其他有充分依据的文件，并对防火性能、铝复合板和 NatHERS 规定了专门的证据规则。",
  summaryCitation: "A5G1–A5G9, pp. 49–56",
  questions: [
    ["What does ‘fit for purpose’ mean under Part A5?", "A5 中“适合用途”是什么意思？", "A material, product, construction form or design must be suitable for its intended job and help achieve the relevant NCC requirements.", "材料、产品、施工形式或设计必须适合其预定功能，并有助于达到相关 NCC 要求。", "A5G1(1), p. 49"],
    ["What three things support fitness for purpose?", "哪些要素支持适合用途？", "Use appropriate evidence under A5G2, the relevant BCA or PCA evidence pathway, and appropriate construction or installation.", "需要 A5G2 规定的适当证据、相关 BCA 或 PCA 证据路径，以及适当的施工或安装。", "A5G1(2), p. 49"],
    ["Does good evidence excuse poor installation?", "良好证据能弥补错误安装吗？", "No. A compliant product can still fail to be fit for purpose if it is constructed or installed incorrectly.", "不能。即使产品本身合规，如果施工或安装错误，仍可能不适合用途。", "A5G1(2)(b), p. 49"],
    ["How should the form of evidence be selected?", "应如何选择证据形式？", "Choose evidence appropriate to the particular material, product, construction form, design and intended use; one form is not automatically suitable for every case.", "应根据具体材料、产品、施工形式、设计和预定用途选择适当证据；一种证据并非自动适用于所有情况。", "A5G2(1), p. 50"],
    ["Can an abridged certificate or report be used?", "可以使用删节版证书或报告吗？", "No. A submitted copy must be a complete, unabridged copy of the original document.", "不可以。提交的副本必须是原文件完整、未经删节的副本。", "A5G2(2), p. 50"],
    ["What recognised evidence can support BCA compliance?", "哪些认可证据可支持 BCA 合规？", "Examples include current CodeMark or accreditation certificates, certification-body certificates, accredited laboratory reports, qualified professional reports and other properly supported documentary evidence.", "示例包括有效的 CodeMark 或认可证书、认证机构证书、认可实验室报告、合资格专业人员报告及其他有充分依据的书面证据。", "A5G3(1), pp. 50–51"],
    ["What must a testing laboratory report explain?", "测试实验室报告必须说明什么？", "It must show the relevant tests, their results and the other information relied on to demonstrate the specific BCA requirement.", "它必须列出相关测试、测试结果以及用于证明具体 BCA 要求的其他资料。", "A5G3(1)(d), p. 50"],
    ["What must a professional certificate or report contain?", "专业人员证书或报告必须包含什么？", "It must state that the requirement is fulfilled and explain the basis, including standards, specifications or other publications relied upon.", "它必须说明已满足要求，并解释依据，包括所依赖的标准、规范或其他出版物。", "A5G3(1)(e), p. 50"],
    ["Can calculation software be supported as evidence?", "计算软件可以作为证据获得支持吗？", "Yes. Documentary evidence can show that a calculation method, including software, complies with the relevant ABCB protocol.", "可以。书面证据可证明包括软件在内的计算方法符合相关 ABCB 协议。", "A5G3(2), pp. 50–51"],
    ["How is a required fire-resistance level determined?", "如何确定要求的耐火等级？", "Where a DTS provision requires an FRL, determine it in accordance with Specifications 1 and 2.", "当 DTS 条文要求耐火等级时，应按照规范 1 和规范 2 确定。", "A5G5, p. 55"],
    ["How are fire hazard properties and non-combustibility demonstrated?", "如何证明火灾危险特性和不燃性？", "Use the nominated test standards and suitable reports for the property involved; minor departures from a tested prototype need an accredited laboratory assessment and stated limitations.", "应使用针对相关性能指定的测试标准和适当报告；若与测试原型有轻微差异，需要认可实验室评估并说明限制条件。", "A5G6, pp. 55–56"],
    ["What special evidence rules cover ceilings, aluminium panels and NatHERS?", "天花板、铝复合板和 NatHERS 有哪些专门证据规则？", "Ceiling resistance to incipient fire spread needs the prescribed test evidence; aluminium composite panels require SA TS 5344 labelling; and software energy ratings require a NatHERS certificate.", "天花板抵抗初期火势蔓延需要规定的测试证据；铝复合板必须按 SA TS 5344 标识；软件能源评级必须有 NatHERS 证书。", "A5G7–A5G9, p. 56"]
  ]
}, {
  id: "a6",
  section: "A",
  title: "A6 Building Classification",
  titleZh: "A6 建筑分类",
  source: "NCC 2025 Volume Two",
  summaryEn: "Part A6 classifies a building or each part of it by its intended purpose, because use determines risk and therefore which NCC requirements apply. Classes 1 and 10 are mainly covered by Volume Two, while Classes 2 to 9 are mainly covered by Volume One. Mixed uses may require separate or multiple classifications, and all relevant requirements must then be met. Classification is a risk decision, not simply a name chosen by the owner.",
  summaryZh: "A6 部分按照建筑或其各部分的预定用途进行分类，因为用途决定风险，也决定适用哪些 NCC 要求。1 类和 10 类主要由第二卷涵盖，2 至 9 类主要由第一卷涵盖。混合用途可能需要分别分类或多重分类，并必须满足所有相关要求。分类是基于风险的判断，而不是业主任意选择的名称。",
  summaryCitation: "A6G1–A6G12, pp. 57–68",
  questions: [
    ["What determines a building's classification?", "什么决定建筑分类？", "Its classification is determined by the purpose for which the building or part is designed, constructed or adapted to be used.", "分类由建筑或其部分被设计、建造或改造后用于什么目的来决定。", "A6G1(1), p. 57"],
    ["Can different parts of one building have different classes?", "一栋建筑的不同部分可以有不同类别吗？", "Yes. Classify each part according to its purpose and apply the requirements appropriate to that classification.", "可以。应按用途对每个部分分类，并应用适合该类别的要求。", "A6G1(2), p. 57"],
    ["How are plant and service rooms classified?", "设备房和服务用房如何分类？", "A room containing a facility that serves the building normally takes the classification of the major part or principal use around it, except an electricity network substation.", "为建筑服务的设备用房通常采用其所在主要部分或主要用途的分类，但电力网络变电站除外。", "A6G1(3) and Exemption (2), p. 57"],
    ["What is the minor-use 10% concession?", "什么是次要用途 10% 优惠？", "A different use occupying less than 10% of a storey's floor area may sometimes take the main classification of that storey.", "占某层建筑面积少于 10% 的不同用途，在某些情况下可采用该层的主要分类。", "A6G1 Exemption (1), pp. 57–58"],
    ["Which uses cannot use the 10% concession?", "哪些用途不能使用 10% 优惠？", "It does not apply to laboratories, Class 9b early childhood centres, or Class 2, 3 or 4 parts.", "它不适用于实验室、9b 类幼儿中心，或 2、3、4 类部分。", "A6G1 Limitation, p. 57"],
    ["What is a Class 1 building?", "什么是 1 类建筑？", "It is a dwelling. Class 1a covers a detached house or certain attached dwellings; Class 1b covers specified small boarding, guest-house, hostel or short-term accommodation uses.", "它是住宅。1a 类包括独立住宅或某些连排住宅；1b 类包括规定规模内的小型寄宿屋、旅馆、宿舍或短期住宿用途。", "A6G2, pp. 58–59"],
    ["What is a Class 2 building?", "什么是 2 类建筑？", "It contains two or more sole-occupancy units, each being a separate dwelling, such as an apartment building.", "它包含两个或以上各自独立作为住宅的单元，例如公寓楼。", "A6G3, p. 59"],
    ["What is a Class 3 building?", "什么是 3 类建筑？", "It is residential accommodation for unrelated people that is not Class 1 or 2, commonly including larger boarding houses, hostels, hotels and similar accommodation.", "它是供无亲属关系人员居住、但不属于 1 类或 2 类的住宿建筑，通常包括较大的寄宿屋、宿舍、酒店等。", "A6G4, pp. 59–60"],
    ["What is a Class 4 part?", "什么是 4 类部分？", "It is the only dwelling in a building otherwise classified as Class 5, 6, 7, 8 or 9.", "它是在其他部分属于 5、6、7、8 或 9 类建筑中的唯一住宅。", "A6G5, p. 60"],
    ["What is a Class 5 building?", "什么是 5 类建筑？", "It is an office building used for professional or commercial purposes, excluding uses assigned to Classes 6 to 9.", "它是用于专业或商业目的的办公建筑，但不包括被归入 6 至 9 类的用途。", "A6G6, p. 60"],
    ["What is a Class 6 building?", "什么是 6 类建筑？", "It is where goods or services are sold directly to the public, such as shops, cafés, restaurants and certain service premises.", "它是向公众直接销售商品或服务的场所，例如商店、咖啡馆、餐厅和某些服务场所。", "A6G7, pp. 60–61"],
    ["What is a Class 7 building?", "什么是 7 类建筑？", "Class 7a is generally a carpark and Class 7b is generally for storage or wholesale display of goods.", "7a 类通常是停车场；7b 类通常用于储存或批发陈列货物。", "A6G8, pp. 62–63"],
    ["What is a Class 8 building?", "什么是 8 类建筑？", "It is a process-type building, including many factories, laboratories and places where goods are produced, repaired, packed, finished or cleaned for sale.", "它是生产加工型建筑，包括许多工厂、实验室，以及生产、修理、包装、加工或清洁待售货物的场所。", "A6G9, pp. 63–64"],
    ["What are the Class 9 sub-classifications?", "9 类有哪些子类别？", "Class 9a covers health-care buildings, 9b covers assembly buildings, and 9c covers residential care buildings.", "9a 类是医疗建筑，9b 类是集会建筑，9c 类是住宿照护建筑。", "A6G10, p. 65"],
    ["What are the Class 10 sub-classifications?", "10 类有哪些子类别？", "Class 10a is a non-habitable building such as a garage, carport or shed; 10b is a non-habitable structure such as a fence, retaining wall or pool; and 10c is a private bushfire shelter.", "10a 类是车库、车棚或棚屋等非居住建筑；10b 类是围栏、挡土墙或泳池等非居住构筑物；10c 类是私人丛林火灾避难所。", "A6G11, p. 66"],
    ["What happens when a building has multiple classifications?", "建筑有多重分类时怎么办？", "A building or part may have more than one classification, but it must comply with every relevant requirement applying to each classification; where requirements conflict, the more stringent outcome applies.", "建筑或其部分可以有多个分类，但必须符合每个分类的所有相关要求；要求冲突时采用更严格的要求。", "A6G12, pp. 67–68"]
  ]
}, {
  id: "a7",
  section: "A",
  title: "A7 United Buildings",
  titleZh: "A7 联合建筑",
  source: "NCC 2025 Volume Two",
  summaryEn: "Part A7 allows adjoining Class 2 to 9 buildings that are connected and used together to be treated as one united building, but only when the whole arrangement complies with the NCC as a single building. If they do not jointly comply, they remain separate and their connections may need fire protection. If a later alteration removes the connection, each resulting building must comply independently.",
  summaryZh: "A7 部分允许相邻且连接并共同使用的 2 至 9 类建筑被视为一栋联合建筑，但前提是整体必须像一栋建筑一样符合 NCC。如果不能整体合规，它们仍是独立建筑，连接处可能需要防火保护。若日后改造取消连接，则分开的每栋建筑都必须独立合规。",
  summaryCitation: "A7G1–A7G2, pp. 69–70",
  questions: [
    ["When are adjoining buildings deemed to be united?", "相邻建筑何时被视为联合建筑？", "They must be connected, used as one building, connected through openings in dividing walls, and together comply as though they were a single building.", "它们必须相互连接、作为一栋建筑使用、通过分隔墙开口连通，并作为一个整体符合单栋建筑的要求。", "A7G1, p. 69"],
    ["Which building classes can use Part A7?", "哪些建筑类别可以使用 A7？", "The united-building provision applies only to Class 2 to 9 buildings.", "联合建筑条文只适用于 2 至 9 类建筑。", "A7G1 Application (2), p. 69"],
    ["What kinds of physical connections can join buildings?", "哪些物理连接方式可以连接建筑？", "Examples include openings through walls, tunnels, bridges and covered walkways, provided the compliance conditions are met.", "示例包括墙体开口、隧道、桥梁和有盖走道，但必须满足合规条件。", "A7G1 explanatory information, p. 69"],
    ["Do united buildings need extra NCC requirements just because they are joined?", "联合建筑是否仅因连接就需要额外 NCC 要求？", "No. If they jointly comply as one building, no additional provisions arise merely from being united; however, elements whose status changes must meet their new requirements.", "不需要。如果整体按一栋建筑合规，不会仅因联合而增加要求；但性质发生变化的构件必须满足新的要求。", "A7G1 explanatory information, p. 69"],
    ["What happens to an external wall that becomes internal after connection?", "连接后外墙变成内墙怎么办？", "It must comply with the NCC requirements for an internal wall in the united building.", "它必须符合联合建筑中内墙的 NCC 要求。", "A7G1 explanatory information, p. 69"],
    ["What if connected buildings do not jointly comply as one building?", "如果连接建筑不能作为整体合规怎么办？", "They remain separate buildings, and connecting openings may require fire doors or other fire-protection measures.", "它们仍被视为独立建筑，连接开口可能需要防火门或其他防火措施。", "A7G1 explanatory information, p. 69"],
    ["What happens when alterations separate a united building?", "改造后联合建筑被分开怎么办？", "Each building that is no longer connected must comply with all requirements applying to it as a separate single building.", "每栋不再连接的建筑都必须作为独立建筑符合其全部适用要求。", "A7G2, p. 69"],
    ["Does the NCC decide ownership or allotment permission for united buildings?", "NCC 是否决定联合建筑的所有权或地块许可？", "No. Separate ownership, allotments and permission to unite are dealt with by the relevant local authorities and other laws.", "不决定。不同所有权、不同地块以及是否允许联合，由相关地方主管机构和其他法律处理。", "A7G1 explanatory information, p. 69"],
    ["Why can a bridge connection produce several compliance options?", "为什么桥梁连接会产生多种合规方案？", "The bridge and buildings may be treated as one united building, three separate buildings, or the bridge may form part of one side. Each arrangement changes fire separation, structural support and egress obligations.", "桥梁和建筑可以作为一栋联合建筑、三栋独立建筑，或让桥梁属于其中一侧。每种安排都会改变防火分隔、结构支撑和疏散义务。", "A7 explanatory example, pp. 69–70"],
    ["What extra issues arise when a bridge crosses a public road?", "桥梁跨越公共道路时会出现哪些额外问题？", "Special approvals, road obstruction, travel distance, independent support and fire separation may all need consideration.", "可能需要考虑特别审批、道路阻碍、疏散距离、独立支撑和防火分隔。", "A7 explanatory example, p. 70"]
  ]
}];
