window.NCC_SECTION_A_V2 = [{
  id: "a1",
  section: "A",
  title: "A1 Interpreting the NCC",
  titleZh: "A1 解读 NCC",
  source: "NCC 2025 Volume Two",
  summaryEn: "Part A1 is the reading framework for the NCC. It defines the scope of each Volume and explains which text is mandatory, how defined words and references must be read, and how Applications, Limitations, Exemptions, Notes and Figures affect a provision.",
  summaryZh: "A1 是阅读 NCC 的基础框架。它界定各卷的范围，并说明哪些文字具有强制性、如何理解定义词和引用，以及适用条款、限制、豁免、注释和图示如何影响条文。",
  summaryCitation: "A1G1–A1G4, pp. 38–40",
  questions: [
    ["A1G1-Q1 — What building classifications, structures and requirements are covered by NCC Volume One, including how its scope differs from Volumes Two and Three?", "A1G1-Q1——NCC 第一卷涵盖哪些建筑分类、构筑物和要求？它与第二卷和第三卷的范围有何不同？", "Volume One is the Building Code of Australia provisions principally applying to Class 2 to Class 9 buildings and structures. Volume Two principally covers Class 1 and Class 10 buildings and structures. Volume Three is the Plumbing Code of Australia and applies to plumbing and drainage systems across building classifications. The project may therefore require more than one Volume when it contains different classifications or plumbing work.", "第一卷是澳大利亚建筑规范中主要适用于 2 至 9 类建筑和构筑物的规定。第二卷主要涵盖 1 类和 10 类建筑及构筑物。第三卷是澳大利亚管道规范，适用于各类建筑的管道和排水系统。因此，当项目包含不同建筑分类或管道工程时，可能需要同时使用多卷。", "A1G1, p. 38"],
    ["A1G1-Q2 — Why must every building and building part be matched to the correct NCC Volume before technical requirements are selected?", "A1G1-Q2——为什么在选择技术要求之前，必须把每栋建筑及其各部分与正确的 NCC 卷册对应？", "The technical requirements are organised by building classification and type of work. Using Volume Two for a Class 2–9 part can omit requirements located in Volume One, while ignoring Volume Three can omit plumbing and drainage requirements. Classification and scope must therefore be settled before selecting a compliance pathway.", "技术要求按建筑分类和工程类型编排。对 2 至 9 类部分错误使用第二卷，可能遗漏第一卷中的要求；忽略第三卷则可能遗漏管道和排水要求。因此，在选择合规路径前必须先确定分类和适用卷册。", "A1G1, p. 38"],
    ["A1G1-Q3 — How should the NCC Volumes be allocated when one development contains Class 2 apartments, Class 6 shops and associated Class 10 structures?", "A1G1-Q3——当一个开发项目包含 2 类公寓、6 类商店和相关 10 类构筑物时，应如何分配 NCC 卷册？", "Classify each building or relevant part first. Apply Volume One to the Class 2 and Class 6 parts. Check A1G2 to determine whether each Class 10 building or structure falls within Volume Two and whether an access exception applies. Apply Volume Three separately to plumbing and drainage work. Also check the applicable jurisdictional variations.", "首先对每栋建筑或相关部分分类。2 类和 6 类部分使用第一卷。根据 A1G2 判断每个 10 类建筑或构筑物是否属于第二卷，以及是否存在无障碍例外。管道和排水工程另行使用第三卷，并检查适用的司法辖区变更。", "A1G1, p. 38"],
    ["A1G2-Q1 — What buildings and structures are covered by Volume Two, including the treatment of Class 1, Class 10a, specified Class 10b structures, Class 10c shelters and access exceptions?", "A1G2-Q1——第二卷涵盖哪些建筑和构筑物，包括 1 类、10a 类、指定 10b 类、10c 类避难所以及无障碍例外？", "Volume Two contains the BCA requirements for Class 1 and Class 10a buildings, specified Class 10b structures and Class 10c private bushfire shelters. Its scope is subject to the access provisions identified by A1G2, meaning some access requirements for particular Class 1b or Class 10 buildings or structures may need to be taken from Volume One rather than relying only on Volume Two.", "第二卷包含适用于 1 类和 10a 类建筑、指定 10b 类构筑物以及 10c 类私人丛林火灾避难所的 BCA 要求。其范围受 A1G2 所列无障碍规定约束，因此某些 1b 类或 10 类建筑、构筑物的无障碍要求可能需要查阅第一卷，不能只依赖第二卷。", "A1G2, p. 38"],
    ["A1G2-Q2 — Why does being classified as Class 10 not automatically mean that every requirement is found only in Volume Two?", "A1G2-Q2——为什么被归为 10 类并不自动意味着所有要求都只在第二卷中？", "A reference to Class 10 includes its subclassifications, but Volume Two's scope identifies which Class 10 structures it covers and preserves specified access exceptions. The structure's use, subclassification and relationship to other buildings must be checked before assuming that Volume Two contains every applicable requirement.", "对 10 类的引用包括其子类别，但第二卷的范围会明确其涵盖哪些 10 类构筑物，并保留指定的无障碍例外。在认定第二卷包含全部适用要求前，必须检查构筑物用途、子类别及其与其他建筑的关系。", "A1G2, p. 38"],
    ["A1G2-Q3 — How would you check Volume Two's scope for a house, garage, retaining wall, swimming pool and private bushfire shelter?", "A1G2-Q3——如何核对住宅、车库、挡土墙、泳池和私人丛林火灾避难所是否属于第二卷？", "Classify the house as Class 1, the garage as Class 10a, the retaining wall and swimming pool as relevant Class 10b structures, and the private bushfire shelter as Class 10c. Confirm that each structure fits A1G2, check any stated access exception, then apply Volume Three to plumbing or drainage and the relevant State or Territory schedule to jurisdictional changes.", "将住宅归为 1 类、车库归为 10a 类、挡土墙和泳池归为相关 10b 类构筑物、私人丛林火灾避难所归为 10c 类。确认各项目符合 A1G2，检查任何无障碍例外，再将第三卷用于管道或排水，并查阅相关州或领地附表。", "A1G2, p. 38"],
    ["A1G3-Q1 — What plumbing and drainage matters are covered by Volume Three, and how does that scope interact with Volumes One and Two?", "A1G3-Q1——第三卷涵盖哪些管道和排水事项？其范围如何与第一卷和第二卷衔接？", "Volume Three is the Plumbing Code of Australia and covers plumbing and drainage installations. It operates alongside the BCA building requirements in Volume One or Volume Two rather than replacing them. A building project must satisfy the applicable building Volume for its classification and Volume Three for relevant plumbing and drainage work.", "第三卷是澳大利亚管道规范，涵盖管道和排水装置。它与第一卷或第二卷的 BCA 建筑要求并行适用，而不是取代这些要求。建筑项目必须按其分类满足相应建筑卷册，并对相关管道和排水工程满足第三卷。", "A1G3, p. 38"],
    ["A1G3-Q2 — Why can a Class 1 or Class 10 project require both Volume Two and Volume Three?", "A1G3-Q2——为什么 1 类或 10 类项目可能同时需要第二卷和第三卷？", "Volume Two regulates the building and structural, fire, health, access and energy matters within its scope. Volume Three separately regulates plumbing and drainage systems. A house does not stop being subject to Volume Three merely because its building requirements are in Volume Two.", "第二卷规范其范围内的建筑、结构、防火、健康、通行和能源事项。第三卷另行规范管道和排水系统。住宅的建筑要求位于第二卷，并不意味着其不受第三卷约束。", "A1G3, p. 38"],
    ["A1G3-Q3 — How should responsibilities be divided for a house containing sanitary plumbing, stormwater drainage and heated-water services?", "A1G3-Q3——对于包含卫生管道、雨水排水和热水服务的住宅，应如何划分适用要求？", "Use Volume Two for the house's building requirements, including building-related damp and weatherproofing provisions. Use Volume Three for the plumbing and drainage installation requirements. Identify interfaces—such as penetrations, waterproofing and drainage disposal—where both building and plumbing obligations must be coordinated rather than assessed in isolation.", "住宅建筑要求使用第二卷，包括与建筑相关的防潮和防风雨规定；管道和排水安装要求使用第三卷。还应识别穿孔、防水和排水处置等接口，因为这些位置需要协调建筑和管道义务，不能孤立评估。", "A1G3, p. 38"],
    ["A1G4-Q1 — How must the NCC be interpreted, including mandatory and informative content, defined terms, context, numerical references, Applications, Limitations, Exemptions, Notes, Figures, classifications and building parts?", "A1G4-Q1——应如何解释 NCC，包括强制性和说明性内容、定义词、上下文、数字引用、适用条款、限制、豁免、注释、图示、建筑分类和建筑部分？", "Introduction and explanatory information assist understanding but are not mandatory requirements. Italicised words use the Schedule 1 definition unless the context indicates otherwise, including relevant jurisdictional definitions. Words and references must be read in context. An Application states where a provision applies; a Limitation narrows it; an Exemption removes compliance in stated circumstances. Notes form part of the provision and give additional instructions. Figures illustrate the text but are not complete design information. References to a classification include its subclassifications unless a specific subclassification is named, and references to a building can apply to the relevant part of a mixed-classification building.", "导言和解释性资料用于帮助理解，但不是强制要求。斜体词采用附表 1 的定义，除非上下文另有含义，并须考虑相关司法辖区定义。文字和引用必须结合上下文理解。适用条款说明条文适用于何处；限制缩小其范围；豁免在指定情况下免除合规。注释构成条文的一部分并提供额外指示。图示用于说明文字，但不是完整设计资料。除非明确指定子类别，对某类别的引用包括其子类别；对建筑的引用也可适用于混合分类建筑的相关部分。", "A1G4, pp. 38–40"],
    ["A1G4-Q2 — What does ‘to the degree necessary’ require, and how should Applications, Limitations and Exemptions change a compliance assessment?", "A1G4-Q2——“在必要程度上”要求什么？适用条款、限制和豁免应如何改变合规评估？", "‘To the degree necessary’ requires assessment of every criterion stated for the actual building and circumstances; after that assessment, a particular measure may not be necessary. Applications, Limitations and Exemptions are mandatory controls on scope. They must be read before applying the main rule because they can activate, narrow or remove the obligation.", "“在必要程度上”要求针对实际建筑和情况评估条文列出的每项标准；评估后，某项具体措施可能并非必要。适用条款、限制和豁免都是控制范围的强制内容，必须在应用主要规则前阅读，因为它们可能启动、缩小或取消义务。", "A1G4(3), p. 39"],
    ["A1G4-Q3 — What interpretation checks should be completed before applying a technical provision to part of a mixed-classification building?", "A1G4-Q3——在将技术条文应用于混合分类建筑的一部分之前，应完成哪些解释检查？", "Confirm the classification and subclassification of the relevant part; check whether the provision refers to the whole building or that part; identify italicised definitions; read all Applications, Limitations, Exemptions and Notes; use Figures only as illustrations; consider ‘to the degree necessary’; and check the relevant jurisdictional variation. Only then select and document the applicable technical requirement.", "确认相关部分的类别和子类别；检查条文是针对整栋建筑还是该部分；识别斜体定义词；阅读所有适用条款、限制、豁免和注释；仅将图示作为说明；考虑“在必要程度上”；并检查相关司法辖区变更。完成这些步骤后，才能选择并记录适用的技术要求。", "A1G4, pp. 38–40"]
  ]
}, {
  id: "a2", section: "A", title: "A2 Compliance with the NCC", titleZh: "A2 遵守 NCC", source: "NCC 2025 Volume Two",
  summaryEn: "Part A2 establishes the permitted compliance pathways and the formal process for Performance Solutions, DTS Solutions and combined solutions.",
  summaryZh: "A2 规定允许采用的合规路径，以及性能解决方案、DTS 方案和组合方案的正式流程。", summaryCitation: "A2G1–A2G4, pp. 41–44",
  questions: [
    ["A2G1-Q1 — What must a solution comply with, and what combinations of Performance and DTS Solutions may be used?","A2G1-Q1——方案必须符合什么要求？可采用哪些性能方案与 DTS 方案组合？","A compliant solution must comply with the Governing Requirements and satisfy every relevant Performance Requirement. It may be a Performance Solution, a DTS Solution, or a combination of both. Selecting a pathway does not remove the obligation to identify and satisfy all applicable requirements.","合规方案必须遵守管理要求并满足所有相关性能要求。方案可以是性能解决方案、DTS 方案，或两者组合。选择某一路径并不会免除识别和满足全部适用要求的义务。","A2G1, p. 41"],
    ["A2G1-Q2 — Why is following a familiar construction method insufficient unless it is connected to an NCC compliance pathway?","A2G1-Q2——为什么熟悉的施工方法若未连接到 NCC 合规路径仍不足以证明合规？","Trade familiarity does not prove that the Governing and Performance Requirements are satisfied. The proposal must either match the applicable DTS provisions, be demonstrated as a Performance Solution using accepted assessment methods, or document which portions use each pathway.","行业熟悉程度不能证明已满足管理要求和性能要求。方案必须符合适用 DTS 条文，或通过认可评估方法证明为性能解决方案，或明确记录各部分所采用的路径。","A2G1, p. 41"],
    ["A2G1-Q3 — How should the pathway be established for a house using DTS framing and a custom external-wall system?","A2G1-Q3——采用 DTS 框架和定制外墙系统的住宅应如何确定合规路径？","Treat the framing as DTS only after confirming it matches every applicable DTS detail. Treat the custom wall as a Performance Solution, identify all affected requirements such as structure, weatherproofing, fire and energy efficiency, and assess it under A2G2. Document the interfaces as a combined solution under A2G4.","只有在确认框架符合所有适用 DTS 细节后，才能将其视为 DTS。定制外墙应作为性能解决方案，识别结构、防风雨、防火和能源效率等所有受影响要求，并按 A2G2 评估；两者接口按 A2G4 记录为组合方案。","A2G1, p. 41"],
    ["A2G2-Q1 — What complete process applies to a Performance Solution?","A2G2-Q1——性能解决方案必须遵循什么完整流程？","The solution must satisfy the relevant Performance Requirements or be at least equivalent to the applicable DTS provisions. Use one or more permitted assessment methods: evidence of suitability, a Verification Method, expert judgement, or comparison with DTS provisions. Identify all affected Performance Requirements. With relevant stakeholders, prepare a performance-based design brief; carry out the analysis; evaluate results against the agreed acceptance criteria; and prepare a final report recording the requirements, methods, analysis, compliance conclusion and conditions or limitations.","方案必须满足相关性能要求，或至少达到适用 DTS 条文的等效水平。可使用一种或多种允许的评估方法：适用性证据、验证方法、专家判断或与 DTS 条文比较。必须识别所有受影响的性能要求，并与相关利益方编制性能化设计简报，完成分析，按商定验收标准评估结果，最后形成报告，记录要求、方法、分析、合规结论以及条件或限制。","A2G2, pp. 41–42"],
    ["A2G2-Q2 — What is the difference between direct satisfaction of a Performance Requirement and equivalence with DTS?","A2G2-Q2——直接满足性能要求与证明 DTS 等效有何区别？","Direct assessment tests the proposal against the outcome expressed by the Performance Requirement. A DTS comparison instead shows that the proposal performs at least as well as the relevant prescriptive benchmark. Either approach still requires suitable evidence, an accepted assessment method and consideration of every affected requirement.","直接评估是把方案与性能要求所表达的结果比较；DTS 等效比较则证明方案至少达到相关规定性基准的性能。两种方式都需要适当证据、认可评估方法，并考虑所有受影响要求。","A2G2(1)–(2), pp. 41–42"],
    ["A2G2-Q3 — How should a custom waterproofing Performance Solution be prepared and documented?","A2G2-Q3——定制防水性能解决方案应如何准备和记录？","Identify H4P1 and any other affected requirements, including structure or durability interfaces. Agree the design brief, acceptance criteria, assessment methods, assumptions and stakeholder roles. Analyse test evidence and installation details, evaluate the result, then issue a final report describing the system, evidence, compliance conclusion, construction controls, inspection needs and limitations.","识别 H4P1 及其他受影响要求，包括结构或耐久性接口。商定设计简报、验收标准、评估方法、假设和利益方职责。分析测试证据和安装细节，评估结果，并发布最终报告，说明系统、证据、合规结论、施工控制、检查要求和限制。","A2G2(3)–(4), p. 42"],
    ["A2G3-Q1 — How does a DTS Solution demonstrate compliance and what assessment methods remain available?","A2G3-Q1——DTS 方案如何证明合规？仍可使用哪些评估方法？","A DTS Solution satisfies the relevant Performance Requirements by complying with all applicable DTS provisions. Compliance with those provisions may be demonstrated using evidence of suitability under Part A5, expert judgement, or another assessment method identified by A2G3 as applicable. Applications, limitations, referenced documents and installation details remain part of the pathway.","DTS 方案通过遵守全部适用 DTS 条文来满足相关性能要求。可使用 A5 的适用性证据、专家判断或 A2G3 允许的其他评估方法证明符合条文。适用范围、限制、引用文件和安装细节仍是该路径的一部分。","A2G3, p. 42"],
    ["A2G3-Q2 — Why can a DTS proposal still require evidence, calculations or expert judgement?","A2G3-Q2——为什么 DTS 方案仍可能需要证据、计算或专家判断？","The DTS text states what must be achieved or constructed, but the project must prove that its actual products, calculations and installation match it. Evidence may be needed for product properties, FRLs, structural capacity, energy performance or referenced-standard compliance; expert judgement cannot replace a mandatory detail without a valid Performance Solution.","DTS 文字说明必须实现或建造什么，但项目仍须证明实际产品、计算和安装与之相符。产品性能、FRL、结构承载力、能源性能或引用标准合规可能需要证据；专家判断不能在没有有效性能方案时取代强制细节。","A2G3(2), p. 42"],
    ["A2G3-Q3 — What must be checked before accepting a proposed wall as DTS?","A2G3-Q3——接受拟建墙体为 DTS 前必须检查什么？","Confirm classification, location and applicable jurisdiction; identify the exact DTS provision and referenced edition; verify materials, dimensions, joints, penetrations, supports and installation; check evidence of suitability; and ensure no variation has changed the prescribed system. Any departure must be resolved rather than ignored.","确认分类、地点和适用司法辖区；确定准确 DTS 条文和引用版本；核实材料、尺寸、接缝、穿孔、支撑和安装；检查适用性证据；并确认没有变更修改规定系统。任何偏离都必须处理，不能忽略。","A2G3, p. 42"],
    ["A2G4-Q1 — How does A2G4 regulate a solution combining Performance and DTS components?","A2G4-Q1——A2G4 如何规范性能方案与 DTS 组成的组合方案？","The Performance component must be assessed under A2G2 and the DTS component under A2G3. The relevant Performance Requirements must be identified for the whole solution, including requirements affected by interactions between components. The documentation must clearly define the boundary and demonstrate that the combined result complies.","性能部分必须按 A2G2 评估，DTS 部分按 A2G3 评估。必须识别整个方案的相关性能要求，包括组件相互作用所影响的要求。文件应明确两种路径的边界，并证明组合结果合规。","A2G4, p. 43"],
    ["A2G4-Q2 — How can a Performance Solution in one NCC Part affect requirements elsewhere?","A2G4-Q2——一个部分中的性能方案如何影响其他 NCC 部分的要求？","A design change can alter structure, fire spread, moisture, energy, access or another system beyond its starting provision. A2G4 therefore requires identification of affected requirements in other Parts instead of assessing one clause in isolation. Interfaces and consequential changes must be included in the brief and final report.","设计变更可能影响起始条文之外的结构、火势蔓延、潮湿、能源、通行或其他系统。因此 A2G4 要求识别其他部分受影响的要求，不能孤立评估一个条款；接口和连带变化必须写入设计简报和最终报告。","A2G4(3), pp. 43–44"],
    ["A2G4-Q3 — How should a house using DTS construction and a fire-separation Performance Solution be assessed?","A2G4-Q3——采用 DTS 施工并对防火分隔使用性能方案的住宅应如何评估？","Document which construction remains DTS and verify it under A2G3. Assess the altered fire separation under A2G2, including spread of fire, structural support, penetrations, alarms and any other affected requirements. Demonstrate that interfaces do not invalidate the DTS work, then combine both conclusions in coordinated project documentation.","记录哪些构造仍采用 DTS，并按 A2G3 核实。按 A2G2 评估改变后的防火分隔，包括火势蔓延、结构支撑、穿孔、报警器及其他受影响要求。证明接口不会使 DTS 工作失效，再把两种结论整合到协调一致的项目文件中。","A2G4, pp. 43–44"]
  ]
}];

for (const replacement of window.NCC_SECTION_A_V2) {
  const existingIndex = window.NCC_CHAPTERS.findIndex((chapter) => chapter.id === replacement.id);
  if (existingIndex >= 0) window.NCC_CHAPTERS[existingIndex] = replacement;
}
